// AUTO-GENERATED by tools/ingest_creature.py — do not edit by hand.
// One entry per creature species. `glb` and every external-texture module are static
// require()s (Metro resolves them at build time). Flat colours are baked into each GLB
// as material factors; only detailed textures (baseColor/normal/emissive) appear here.
// The renderer decodes each PNG to a THREE.DataTexture on device (see BuddyView.tsx).

export type ExternalSlot = 'map' | 'normalMap' | 'emissiveMap';
export interface SpeciesEntry {
  id: string;
  displayName: string;
  glb: number;
  externalTextures: Record<string, Partial<Record<ExternalSlot, number>>>;
}

export const SPECIES_REGISTRY = {
  boulder: {
    id: 'boulder',
    displayName: 'Boulder',
    glb: require('@/assets/buddies/boulder/model/boulder.glb'),
    externalTextures: {
      mat_face_screen: { map: require('@/assets/buddies/boulder/textures/tex_8.png'), emissiveMap: require('@/assets/buddies/boulder/textures/tex_9.png') },
    },
  },
  chroma: {
    id: 'chroma',
    displayName: 'Chroma',
    glb: require('@/assets/buddies/chroma/model/chroma.glb'),
    externalTextures: {
      mat_screen: { map: require('@/assets/buddies/chroma/textures/tex_12.png'), emissiveMap: require('@/assets/buddies/chroma/textures/tex_13.png') },
    },
  },
  dozer: {
    id: 'dozer',
    displayName: 'Dozer',
    glb: require('@/assets/buddies/dozer/model/dozer.glb'),
    externalTextures: {
      mat_face_screen: { map: require('@/assets/buddies/dozer/textures/tex_10.png'), emissiveMap: require('@/assets/buddies/dozer/textures/tex_11.png') },
    },
  },
  dragon: {
    id: 'dragon',
    displayName: 'Dragon',
    glb: require('@/assets/buddies/dragon/model/dragon.glb'),
    externalTextures: {
      mat_face_screen: { map: require('@/assets/buddies/dragon/textures/tex_16.png'), emissiveMap: require('@/assets/buddies/dragon/textures/tex_17.png') },
    },
  },
  glow: {
    id: 'glow',
    displayName: 'Glow',
    glb: require('@/assets/buddies/glow/model/glow.glb'),
    externalTextures: {
      mat_face_screen: { map: require('@/assets/buddies/glow/textures/tex_14.png'), emissiveMap: require('@/assets/buddies/glow/textures/tex_15.png') },
    },
  },
  heart: {
    id: 'heart',
    displayName: 'Heart',
    glb: require('@/assets/buddies/heart/model/heart.glb'),
    externalTextures: {
      mat_face_screen: { map: require('@/assets/buddies/heart/textures/tex_14.png'), emissiveMap: require('@/assets/buddies/heart/textures/tex_15.png') },
    },
  },
  hoarder: {
    id: 'hoarder',
    displayName: 'Hoarder',
    glb: require('@/assets/buddies/hoarder/model/hoarder.glb'),
    externalTextures: {
      mat_face_screen: { map: require('@/assets/buddies/hoarder/textures/tex_16.png'), emissiveMap: require('@/assets/buddies/hoarder/textures/tex_17.png') },
    },
  },
  hopper: {
    id: 'hopper',
    displayName: 'Hopper',
    glb: require('@/assets/buddies/hopper/model/hopper.glb'),
    externalTextures: {
      mat_body: { map: require('@/assets/buddies/hopper/textures/body_basecolor.png'), normalMap: require('@/assets/buddies/hopper/textures/body_normal.png') },
      mat_belly: { map: require('@/assets/buddies/hopper/textures/belly_basecolor.png'), normalMap: require('@/assets/buddies/hopper/textures/belly_normal.png') },
      mat_inner_ear: { map: require('@/assets/buddies/hopper/textures/inner_ear_basecolor.png'), normalMap: require('@/assets/buddies/hopper/textures/inner_ear_normal.png') },
      mat_frame: { normalMap: require('@/assets/buddies/hopper/textures/frame_normal.png') },
      mat_face: { map: require('@/assets/buddies/hopper/textures/face_neutral_basecolor.png'), normalMap: require('@/assets/buddies/hopper/textures/face_normal.png'), emissiveMap: require('@/assets/buddies/hopper/textures/face_neutral_emissive.png') },
      mat_portal: { map: require('@/assets/buddies/hopper/textures/portal_basecolor.png'), normalMap: require('@/assets/buddies/hopper/textures/portal_normal.png'), emissiveMap: require('@/assets/buddies/hopper/textures/portal_emissive.png') },
    },
  },
  horse: {
    id: 'horse',
    displayName: 'Horse',
    glb: require('@/assets/buddies/horse/model/horse.glb'),
    externalTextures: {
      mat_face_screen: { map: require('@/assets/buddies/horse/textures/tex_13.png'), emissiveMap: require('@/assets/buddies/horse/textures/tex_14.png') },
    },
  },
  jumper: {
    id: 'jumper',
    displayName: 'Jumper',
    glb: require('@/assets/buddies/jumper/model/jumper.glb'),
    externalTextures: {
      mat_face_screen: { map: require('@/assets/buddies/jumper/textures/tex_13.png'), emissiveMap: require('@/assets/buddies/jumper/textures/tex_14.png') },
    },
  },
  magnet: {
    id: 'magnet',
    displayName: 'Magnet',
    glb: require('@/assets/buddies/magnet/model/magnet.glb'),
    externalTextures: {
      mat_face_screen: { map: require('@/assets/buddies/magnet/textures/tex_13.png'), emissiveMap: require('@/assets/buddies/magnet/textures/tex_14.png') },
    },
  },
  mist: {
    id: 'mist',
    displayName: 'Mist',
    glb: require('@/assets/buddies/mist/model/mist.glb'),
    externalTextures: {
      mat_face_screen: { map: require('@/assets/buddies/mist/textures/tex_10.png'), emissiveMap: require('@/assets/buddies/mist/textures/tex_11.png') },
    },
  },
  nimbus: {
    id: 'nimbus',
    displayName: 'Nimbus',
    glb: require('@/assets/buddies/nimbus/model/nimbus.glb'),
    externalTextures: {
      mat_face_screen: { map: require('@/assets/buddies/nimbus/textures/tex_11.png'), emissiveMap: require('@/assets/buddies/nimbus/textures/tex_12.png') },
    },
  },
  shell: {
    id: 'shell',
    displayName: 'Shell',
    glb: require('@/assets/buddies/shell/model/shell.glb'),
    externalTextures: {
      mat_face_screen: { map: require('@/assets/buddies/shell/textures/tex_13.png'), emissiveMap: require('@/assets/buddies/shell/textures/tex_14.png') },
    },
  },
  shy: {
    id: 'shy',
    displayName: 'Shy',
    glb: require('@/assets/buddies/shy/model/shy.glb'),
    externalTextures: {
      mat_face_screen: { map: require('@/assets/buddies/shy/textures/tex_10.png'), emissiveMap: require('@/assets/buddies/shy/textures/tex_11.png') },
    },
  },
  storm: {
    id: 'storm',
    displayName: 'Storm',
    glb: require('@/assets/buddies/storm/model/storm.glb'),
    externalTextures: {
      mat_screen: { map: require('@/assets/buddies/storm/textures/tex_11.png'), emissiveMap: require('@/assets/buddies/storm/textures/tex_12.png') },
    },
  },
  thorn: {
    id: 'thorn',
    displayName: 'Thorn',
    glb: require('@/assets/buddies/thorn/model/thorn.glb'),
    externalTextures: {
      mat_face_screen: { map: require('@/assets/buddies/thorn/textures/tex_12.png'), emissiveMap: require('@/assets/buddies/thorn/textures/tex_13.png') },
    },
  },
} satisfies Record<string, SpeciesEntry>;

export type SpeciesId = keyof typeof SPECIES_REGISTRY;
export const SPECIES_IDS = Object.keys(SPECIES_REGISTRY) as SpeciesId[];
